name: BuildWindows

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Git Sumbodule Update
      run: |
        git submodule update --init
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/buildWindows -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build app for release
      working-directory: ${{github.workspace}}/buildWindows
      run: msbuild .\C2.sln
