name: Release

on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: write

jobs:
  buildAndRelease:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    # Update references
    - name: Git Sumbodule Update
      run: |
        git submodule update --init

    - name: Get Conan
      # You may pin to the exact commit or the version.
      # uses: turtlebrowser/get-conan@c171f295f3f507360ee018736a6608731aa2109d
      uses: turtlebrowser/get-conan@v1.2

    - name: Create default profile
      run: copy .\conan.profile $HOME\.conan2\profiles\default
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
      with:
        msbuild-architecture: x64
    
    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -B ${{github.workspace}}/build -DWITH_TESTS=OFF

    - name: Build app for release
      working-directory: ${{github.workspace}}/build
      run: msbuild .\C2Implant.sln /property:Configuration=Release -m:16

    - name: Prep release
      shell: pwsh
      run: |
        del .\Release\Beacons\.gitignore
        del .\Release\Modules\.gitignore
        Compress-Archive -Path .\Release -DestinationPath .\Release.zip

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Release.zip
        asset_name: Release.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Windows beacons and modules"

