name: Tests

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  buildAndTest:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    # Update references
    - name: Git Sumbodule Update
      run: |
        git submodule update --init

    - name: Get Conan
      # You may pin to the exact commit or the version.
      # uses: turtlebrowser/get-conan@c171f295f3f507360ee018736a6608731aa2109d
      uses: turtlebrowser/get-conan@v1.2

    - name: Create default profile
      run: conan profile detect
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
      with:
        msbuild-architecture: x64
    
    - name: Configure CMake for tests
      run: cmake -G "Visual Studio 17 2022" -B ${{github.workspace}}/build -DWITH_TESTS=ON

    - name: Build app for tests
      working-directory: ${{github.workspace}}/build
      run: msbuild .\C2Implant.sln /property:Configuration=Release -m:16

    - name: Run unit tests
      run: ctest --test-dir build -C Release
      
    - name: Configure CMake like the release
      run: cmake -G "Visual Studio 17 2022" -B ${{github.workspace}}/buildRelease -DWITH_TESTS=OFF

    - name: Build app like the release
      working-directory: ${{github.workspace}}/buildRelease
      run: msbuild .\C2Implant.sln /property:Configuration=Release -m:16


